name: Lint Action

on:
  pull_request:
    branches: [main] 

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint with Lint Action
        uses: wearerequired/lint-action@v2.3.0
